export var UPDATE_RATING_BY_ID = 'UPDATE_RATING_BY_ID';
export const FETCH_LIST_REQUEST = 'FETCH_LIST_REQUEST';
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS';
export const FETCH_LIST_FAILURE = 'FETCH_LIST_FAILURE';

export const ADD_RATING = 'ADD_RATING';
export const SORT_LIST_ON_RATINGS = 'SORT_LIST_ON_RATINGS';